# action.yml
name: 'Mesh Release Action'
description: 'Update mesh app'
inputs:
  version:
    description: 'App version'
    required: true
  token:
    description: 'GitHub Private Access Token'
    required: true
  app:
    description: 'App name (defaults to current folder name)'
    required: false
  repo:
    description: 'App configuration repository'
    required: false
    default: github.com/brudi/catalog-mesh.git
  ref:
    description: 'Git ref to checkout'
    required: false
    default: 'master'
  path:
    description: 'Path to app configuration in repo'
    required: false
  image:
    description: 'Path to docker repo image'
    required: false
  imageBase:
    description: 'Base path to docker repo images'
    required: false
  images:
    description: 'Comma separated list of image names to replace'
    required: false
  overlay:
    description: 'Specific overlay to release'
    required: false
  push:
    description: 'Push the changes of the app repo itself. By default, changes are pushed to the `repo` only.'
    required: false
  commit:
    description: 'Commit all release changes. True by default.'
    required: false
  amend:
    description: 'Amend the app changes to the last commit. Creates a new commit by default. Only available when `push` is set to true.'
    required: false
  merge:
    description: 'Git ref used to merge after release. Does not merge by default.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app }}
    - ${{ inputs.version }}
    - ${{ inputs.token }}
    - ${{ inputs.repo }}
    - ${{ inputs.ref }}
    - ${{ inputs.path }}
    - ${{ inputs.image }}
    - ${{ inputs.imageBase }}
    - ${{ inputs.images }}
    - ${{ inputs.overlay }}
    - ${{ inputs.commit }}
    - ${{ inputs.amend }}
    - ${{ inputs.push }}
    - ${{ inputs.merge }}
