# action.yml
name: 'Mesh Release Action'
description: 'Update mesh app'
inputs:
  version:
    description: 'App version'
    required: true
  token:
    description: 'GitHub Private Access Token'
    required: true
  app:
    description: 'App name (defaults to current folder name)'
    required: false
  repo:
    description: 'App configuration repository'
    required: false
    default: github.com/brudi/catalog-mesh.git
  ref:
    description: 'Git ref to checkout'
    required: false
    default: 'master'
  path:
    description: 'Path to app configuration in repo'
    required: false
  image:
    description: 'Path to docker repo image'
    required: false
  imageBase:
    description: 'Base path to docker repo images'
    required: false
  images:
    description: 'Comma separated list of image names to replace'
    required: false
  overlay:
    description: 'Specific overlay to release'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app }}
    - ${{ inputs.version }}
    - ${{ inputs.token }}
    - ${{ inputs.repo }}
    - ${{ inputs.ref }}
    - ${{ inputs.path }}
    - ${{ inputs.image }}
    - ${{ inputs.imageBase }}
    - ${{ inputs.images }}
    - ${{ inputs.overlay }}
