# action.yml
name: 'Mesh Release Action'
description: 'Update mesh app'
inputs:
  version:
    description: 'App version'
    required: true
  token:
    description: 'GitHub Private Access Token'
    required: true
  app:
    description: 'App name (defaults to current folder name)'
    required: false
  repo:
    description: 'App configuration repository'
    required: false
    default: github.com/brudi/catalog-solutions.git
  ref:
    description: 'Git ref to checkout'
    required: false
    default: 'master'
  path:
    description: 'Path to app configuration in repo'
    required: false
  kustimization:
    description: 'Kustomization file'
    required: false
    default: 'kustomization.yaml'
  tag-path:
    description: 'Explicit path to image tag value to replace'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app }}
    - ${{ inputs.version }}
    - ${{ inputs.token }}
    - ${{ inputs.repo }}
    - ${{ inputs.ref }}
    - ${{ inputs.path }}
    - ${{ inputs.kustomization }}
    - ${{ inputs.tag-path }}
