apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: next-

images:
- name: docker.pkg.github.com/brudi/sites/sites-www
  newTag: 60d74c9

resources:
- ../../base

patchesStrategicMerge:
- virtualservice.yaml
- deploy.yaml
- service.yaml
